In [1]:
import numpy as np 
import pandas as pd
from scipy.stats import stats
import math
from scipy.stats import chi2_contingency
from scipy.stats import chi2

In [2]:
ratio =pd.read_csv('C:\\Nikhil\\\DS\\ML\\Assignments\\Hypothesis testing\\BuyerRatio.csv')
ratio.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [3]:
ratio=ratio.drop(['Observed Values'], axis=1)

In [4]:
males = ratio.iloc[0]
females = ratio.iloc[1]

In [5]:
males = np.array(males)
females = np.array(females)

In [6]:
observed_values = np.array([males,females])

In [7]:
observed_values 

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [8]:
val = chi2_contingency(ratio)

In [9]:
val

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [10]:
expected_values = val[3]
expected_values

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [11]:
# degree of freedom = (no of rows-1) * (no of columns)
ddof = (2-1)*(4-1)
print('Degree of freedom = ',ddof)
alpha = 0.05

Degree of freedom =  3


In [12]:
# now applying the chi square test
chi_square = sum([((o-e)**2)/e for o,e in zip(observed_values,expected_values)])
chi_square_stats=chi_square[0]+chi_square[1]+chi_square[2]+chi_square[3]

In [13]:
chi_square_stats

1.5959455386610577

In [14]:
critical_value = chi2.ppf(q = 1-alpha,df=ddof)
print('Critical value is :',critical_value)

Critical value is : 7.814727903251179


In [15]:
p_value = chi2.cdf(x=chi_square_stats, df= ddof)
print('p-value : ',p_value)
print('Significance level : ',alpha)
print('Degree of freedom : ',ddof)

p-value :  0.3396905092908118
Significance level :  0.05
Degree of freedom :  3


In [16]:
if chi_square_stats>=critical_value:
    print('Reject null hypothesis and accept alternate hypothesis, All proportions are equal')
else:
    print('Reject alternate hypothesis and accept null hypothesis, Not all proportions are equal')

if p_value<=alpha:
    print('Reject null hypothesis and accept alternate hypothesis, All proportions are equal')
else:
    print('Reject alternate hypothesis and accept null hypothesis, Not all proportions are equal')

Reject alternate hypothesis and accept null hypothesis, Not all proportions are equal
Reject alternate hypothesis and accept null hypothesis, Not all proportions are equal
