In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import scipy
from scipy.stats import chi2_contingency
from scipy.stats import chi2

In [2]:
# Null hypothesis is that defective percentage does not varies from  center to center.
# Alternate hypothesis is that defective percentage varies from center to center.

In [3]:
data = pd.read_csv('C:\\Nikhil\\DS\\ML\\Assignments\\Hypothesis testing\\Costomer+OrderForm.csv')
data.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [4]:
data.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [5]:
data.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [6]:
data.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [7]:
data.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [8]:
# So now we have to make a contingency table
observed_values = np.array([[29,33,31,20],[271,267,269,280]])
observed_values

array([[ 29,  33,  31,  20],
       [271, 267, 269, 280]])

In [9]:
val = chi2_contingency(observed_values)
val

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[ 28.25,  28.25,  28.25,  28.25],
        [271.75, 271.75, 271.75, 271.75]]))

In [10]:
expected_values = val[3]
expected_values

array([[ 28.25,  28.25,  28.25,  28.25],
       [271.75, 271.75, 271.75, 271.75]])

In [11]:
# degree of freedom = (no of rows-1) * (no of columns)
ddof = (2-1)*(4-1)
print('Degree of freedom = ',ddof)
alpha = 0.05

Degree of freedom =  3


In [12]:
# now applying the chi square test
chi_square = sum([((o-e)**2)/e for o,e in zip(observed_values,expected_values)])
chi_square_stats=chi_square[0]+chi_square[1]+chi_square[2]+chi_square[3]
chi_square_stats

3.8589606858203545

In [13]:
critical_value = chi2.ppf(q = 1-alpha,df=ddof)
print('Critical value is :',critical_value)

Critical value is : 7.814727903251179


In [ ]:
statistic_tele , p_value_tele = stats.chisquare(observed_tele, expected_tele,df_tab)
print("Statistic_tele = ",statistic_tele,'\n', 'p_value_tele =',p_value_tele)